INSERT INTO artista (nome, tipo) VALUES
('Chico Buarque', 'CANTOR'),
('Caetano Veloso', 'CANTOR'),
('Gilberto Gil', 'CANTOR'),
('Elis Regina', 'CANTORA'),
('Maria Bethânia', 'CANTORA'),
('Djavan', 'CANTOR'),
('Milton Nascimento', 'CANTOR'),
('Legião Urbana', 'BANDA'),
('Titãs', 'BANDA'),
('Os Paralamas do Sucesso', 'BANDA'),
('Skank', 'BANDA'),
('Capital Inicial', 'BANDA'),
('Ivete Sangalo', 'CANTORA'),
('Anitta', 'CANTORA'),
('Marisa Monte', 'CANTORA'),
('Zeca Pagodinho', 'CANTOR'),
('Seu Jorge', 'CANTOR'),
('Rita Lee', 'CANTORA'),
('Engenheiros do Hawaii', 'BANDA'),
('Barão Vermelho', 'BANDA');
